# Generated by Django 3.0.5 on 2020-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20200417_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vlan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
